Somke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -402,9 +402,7 @@ jobs:
               npm install
               npm run build      
               cd ..
-              # Tar the directory
               tar -C backend -czvf artifact.tar.gz .
-
               cp artifact.tar.gz .circleci/ansible/roles/deploy/files
       - run:
           name: deploy backend
@@ -423,28 +421,45 @@ jobs:
       - revert-migrations
       - destroy_environment
 
-#   smoke-test:
-#     docker:
-#       # Lightweight Docker image 
-#     steps:
-#       # Checkout code from git
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             # your code here
-#       - run:
-#           name: Get backend url
-#           command: |
-#             # your code here
-#       - run:
-#           name: Backend smoke test.
-#           command: |
-#             # your code here
-#       - run:
-#           name: Frontend smoke test.
-#           command: |
-#             # your code here
-#       # Here's where you will add some code to rollback on failure  
+  smoke-test:
+    docker:
+      - image: cimg/node:13.8.0
+    steps:
+      - checkout
+      - install-awscli
+      # - run:
+      #     name: Install dependencies
+      #     command: |
+      #       # your code here
+      - run:
+          # Fetch and prepare the BACKEND_IP env var
+          BACKEND_IP=$(aws ec2 describe-instances \
+          --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+          --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+
+          export API_URL="http://${BACKEND_IP}:3030"
+          echo "${API_URL}"
+          if curl "${API_URL}/api/status" | grep "ok"
+          then
+              return 0
+          else
+              return 1
+          fi
+ 
+      - run:
+          name: Frontend smoke test.
+          command: |
+            FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
+            if curl -s $FRONTEND_WEBSITE | grep "welcome"
+            then
+              exit 0
+            else
+              exit 1
+            fi
+
+      # Here's where you will add some code to rollback on failure
+      - revert-migrations
+      - destroy_environment
 
 #   cloudfront-update:
 #     docker:
@@ -519,8 +534,8 @@ workflows:
           requires: [run-migrations]
       - deploy-backend:
           requires: [run-migrations]
-      # - smoke-test:
-      #     requires: [deploy-backend, deploy-frontend]
+      - smoke-test:
+          requires: [deploy-backend, deploy-frontend]
       # - cloudfront-update:
       #     requires: [smoke-test]
       # - cleanup:
